# Architecture identifier.
arch = "x86_64" # str
# Platform identifier.
platform = "x86_64-qemu-q35" # str
# Number of CPUs
smp = 1 # uint
# Stack size of each task.
task-stack-size = 0x40000 # uint
# Number of timer ticks per second (Hz). A timer tick may contain several timer
# interrupts.
ticks-per-sec = 100 # uint

#
# Device specifications
#
[devices]
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    [0xb000_0000, 0x1000_0000],
    [0xfe00_0000, 0xc0_0000],
    [0xfec0_0000, 0x1000],
    [0xfed0_0000, 0x1000],
    [0xfee0_0000, 0x1000]
] # [(uint, uint)]
# End PCI bus number.
pci-bus-end = 0xff # uint
# Base physical address of the PCIe ECAM space (should read from ACPI 'MCFG' table).
pci-ecam-base = 0xb000_0000 # uint
# PCI device memory ranges (not used on x86).
pci-ranges = [] # [(uint, uint)]
# Timer interrupt frequencyin Hz. (4.0GHz)
timer-frequency = 4_000_000_000 # uint
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = [] # [(uint, uint)]

#
# Platform configs
#
[plat]
# Platform family.
family = "x86-pc" # str
# Kernel address space base.
kernel-aspace-base = "0xffff_8000_0000_0000" # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_7fff_ffff_f000" # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x20_0000 # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_8000_0020_0000" # uint
# The size of the kernel stack.
kernel-stack-size = 0x40000
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0 # uint
# Base address of the whole physical memory.
phys-memory-base = 0 # uint
# Size of the whole physical memory. (128M)
phys-memory-size = 0x800_0000 # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_8000_0000_0000" # uint
# The lowest address of the user heap.
user-heap-base = 0x4000_0000
# The size of the user heap.
user-heap-size = 0x1_0000
# The base address for user interpreter.
user-interp-base = 0x400_0000
# The base address of the user space.
user-space-base = 0x1000
# The size of the user space.
user-space-size = 0x7fff_ffff_f000
# The size of the user stack.
user-stack-size = 0x1_0000
# The highest address of the user stack.
user-stack-top = 0x7fff_0000_0000
